service: my-serverless-app01
frameworkVersion: '3'

plugins:
  - serverless-s3-sync
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-northeast-1

functions:
  hello:
    handler: handler.hello

resources:
  Resources:
    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: sls-static-site.com
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: error.html

    StaticSiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticSite
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
              - s3:GetObject
              Resource:
                Fn::Join: ["", ["arn:aws:s3:::",{"Ref": "StaticSite"},"/*"]]

custom:
  s3Sync:
    - bucketName: sls-static-site.com
      localDir: /static
  customDomain:
    hostsZoneId: ${process.env.AWS_HOSTZONE_ID}
    domainName: ${process.env.AWS_DOMAIN_NAME}
    certificateName: ${process.env.AWS_CERT_NAME}
    certificateArn: ${process.env.AWS_CERT_ARN}
    basePath: ''
    stage: dev
    createRoute53Record: true